mysite/mysite/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('grappelli/', include('grappelli.urls')),
    path('', include('news.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('summernote/', include('django_summernote.urls')),
    path('captcha/', include('captcha.urls')),
    ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,document_root=settings.MEDIA_ROOT)
    import mimetypes

    import debug_toolbar

    mimetypes.add_type("application/javascript", ".js", True)
    urlpatterns = [
                      path('__debug__/', include(debug_toolbar.urls)),
                  ] + urlpatterns

mysite/news/urls.py
import django.views.generic
from django.urls import path

from . import auth, autor, views

app_name = 'news'
urlpatterns = [
    path('likes/<int:news_id>/', views.add_like, name='add'),
    path('', views.index, name='index'),
    path('<int:pk>/', views.detail, name='detail'),
    path('category/<int:category_id>', views.category, name='category'),
    path('create/', autor.NewsCreate.as_view(), name='create'),
    path('<int:pk>/update', autor.NewsUpdateView.as_view(), name='update'),
    path('<int:pk>/del', autor.NewsDeleteView.as_view(), name='delete'),
    path('search/', views.search, name='search'),
    path('login/', auth.user_login, name='account_login'),
    path('register/', auth.registr, name='account_signup'),
    path('logout/', auth.user_logout, name='account_logout'),
    path('validate/<int:user_id>/', auth.valid, name="account_validate"),
    path('validate/', auth.emailvalid, name="emailvalid"),
    path('forgot_password', auth.forgot_password, name="forgot_password"),
    path('password_value/<int:user_id>', auth.password_value, name="password_value"),
]

mysite/news/models.py
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.contenttypes.fields import GenericRelation
from django.db import models
from django.utils import timezone


class Account(models.Model):
    user = models.OneToOneField(User,on_delete = models.CASCADE,
                                primary_key = True)
    code = models.CharField(max_length=50)
    created_at = models.DateTimeField(default=timezone.now,
                                      verbose_name="Дата публикации")


class Likes(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.CASCADE)
    news = models.ForeignKey("News",
                             on_delete=models.CASCADE)


class Key_word(models.Model):
    title = models.CharField(max_length=30)

    def __str__(self):
        return self.title

    class Meta:
        verbose_name = "ключевое слово"
        verbose_name_plural = "Ключевые слова"


class Ip(models.Model):
    ip = models.CharField(max_length=100,)

    def __str__(self):
        return self.ip

    class Meta:
        verbose_name = "ip"
        verbose_name_plural = "ip"


class News(models.Model):
    autor = models.ForeignKey(User, on_delete=models.CASCADE,blank = True,
                              null=True, verbose_name="Автор")
    title = models.CharField(max_length=200, verbose_name='Наименование')
    content = models.TextField(blank=True, verbose_name='Контент')
    created_ad = models.DateTimeField(default=timezone.now,
                                      verbose_name="Дата публикации")
    title_content = models.CharField(max_length=200,
                                     verbose_name="Завлекающая инфомация")
    updated_ad = models.DateTimeField(auto_now=True,
                                      verbose_name="Обновлено")
    photo = models.ImageField(upload_to='photos/%Y/%m/%d/',
                              verbose_name="Фото", blank=True)
    is_published = models.BooleanField(default=True,
                                       verbose_name="Опубликовано")
    category = models.ForeignKey('Category', on_delete=models.PROTECT,
                                 null=True, verbose_name="Категория")
    views = models.ManyToManyField(Ip, related_name="post_views",
                                   blank=True)
    key_word = models.ManyToManyField(Key_word, blank=True)

    def get_absolute_url(self):
        return f'/{self.id}'

    def __str__(self):
        return self.title

    def total_views(self):
        return self.views.count()


    def total_likes(self):
        return self.likes_set.count()

    class Meta:
        verbose_name = "Новость"
        verbose_name_plural = "Новости"
        ordering = ['-created_ad']

    def Контент(self,):
        return self.content[:35]
    Контент.short_content = "Content"


class Category(models.Model):
    title = models.CharField(max_length=150,db_index=True,
                             verbose_name='Наименование категории ')

    class Meta:
        verbose_name = "Категорию"
        verbose_name_plural = "Категории"
        ordering = ['-pk']

    def __str__(self):
        return self.title

mysite/news/forms.py
from captcha.fields import CaptchaField, CaptchaTextInput
from django import forms
from django.contrib.auth.forms import AuthenticationForm, UserCreationForm
from django.contrib.auth.models import User
from django.forms import (DateTimeInput, FileInput, ModelForm, Select,
                          Textarea, TextInput)
from django_summernote.widgets import SummernoteInplaceWidget, SummernoteWidget

from .models import Category, News


class PasswordValidForm(forms.Form):
    code = forms.CharField(max_length=50, label='Код подтвержения',
                           widget=forms.TextInput(attrs={'class': 'form-control w-25'}))

    password1 = forms.CharField(label='Пароль',widget=forms.PasswordInput(
        attrs={"class": "form-control w-25",
               "placeholder": "Пароль"
               }
    ))
    password2 = forms.CharField(label='Пароль повторно',widget=forms.PasswordInput(
        attrs={"class": "form-control w-25",
               "placeholder": "Подтверждение пароля",
               }
    ))


class EmailValidForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={"class": "form-control w-25",
               "placeholder": "E-mail"
               }
    ))
    captcha = CaptchaField(error_messages={'invalid': 'Неверный код с картинки'},
        widget=CaptchaTextInput(
        attrs={"placeholder": "Код с картинки"}
    ))

class CodeVailForm(forms.Form):
    code = forms.CharField( max_length=50, label='Код подтвержения',
                           widget=forms.TextInput(attrs={'class': 'form-control w-25'}))


class loginForm(AuthenticationForm):
    username = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control w-25",
               "placeholder": "Имя Пользователя"
               }
    ))
    password = forms.CharField(widget=forms.PasswordInput(
        attrs={
            "class": "form-control ml-25 w-25",
            "placeholder": "Пароль"}
    ))
    captcha = CaptchaField(error_messages={'invalid': 'Неверный код с картинки'},
        widget=CaptchaTextInput(
        attrs={"placeholder": "Код с картинки"}
    ))
    error_messages = {
        'invalid_login': ("Неверный логин или пароль"),
        'inactive': ("This account is inactive."),
        "error_message" : ("Неверный код с картинки")

    }


class RegistrForm(UserCreationForm ):
    username = forms.CharField(widget=forms.TextInput(
        attrs={"class": "form-control w-25",
               "placeholder":"Имя Пользователя"}

    ))
    password1 = forms.CharField(widget=forms.PasswordInput(
        attrs={"class": "form-control w-25",
               "placeholder":"Пароль"
               }
    ))
    password2 = forms.CharField(widget=forms.PasswordInput(
        attrs={"class": "form-control w-25",
               "placeholder":"Подтверждение пароля",
               }
    ))
    email = forms.EmailField(widget=forms.EmailInput(
        attrs={"class": "form-control w-25",
               "placeholder":"E-mail"
               }
    ))
    captcha = CaptchaField(widget=CaptchaTextInput(
        attrs={"placeholder": "Код с картинки"}
    ))

    class Meta:
        model = User
        fields = {"username", "email", "password1", "password2"}


class SomeForm(forms.Form):
    content = forms.CharField(widget=SummernoteWidget(
        attrs={'summernote': {'width': '50%', 'height': '400px'}}))  # instead of forms.Textarea


class imgForm(ModelForm):
    class Meta:
        # Название модели на основной
        # которой создается форма
        model = News
        # Включаем все поля с модели в форму
        fields = [
            "title",
            "title_content",
            "content",
            "created_ad",
            "photo",
            "category",
            "key_word"
        ]

        widgets = {
            'content': SummernoteWidget(attrs={
                'summernote': {'width': '99.7%', 'height': '600px'}
            }),
            'title': TextInput(attrs={
                'class': 'form-control  w-25 ',
                'placeholder': 'название статьи'
            }),
            "title_content": TextInput(attrs={
                'class': 'form-control  w-75 ',
                'placeholder': 'завлекающая информация'
            }),
            """"content": Textarea(attrs={
                'class': 'form-control',
                'placeholder': 'текст статьи'
            }),"""
            "created_ad": DateTimeInput(attrs={
                'class': 'form-control ',
            }),
            "photo": FileInput(attrs={
                'class': 'form-control  w-25',
            }),
            "category" : Select({
                'class': 'form-control w-25',
            }),


        }

mysite/news/views.py
from django.contrib import messages
from django.core.cache import cache
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import get_object_or_404, redirect, render

from mysite.settings import *

from .models import Account, Category, Ip, Likes, News


def search(request):
    q = request.GET.get('q')
    all_category = cache.get_or_set("all_category",Category.objects.all(),100)

    if q:
        news = News.objects.filter(
            Q(title__icontains=q) | Q(content__icontains=q) | Q(title_content__icontains=q)
        )
        if not news:
            messages.success(request, f"ничего не найдено по вашему запросу ({q})")
        return render(request, "news/search.html", {
            "news": news,
            "all_category": all_category,
        })
    return redirect('/')


def index(request):
    news = cache.get_or_set("news", News.objects.select_related('autor').all(), 0)
    all_category = cache.get_or_set("all_category", Category.objects.all(), 100)

    paginator = Paginator(news, 5)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)

    return render(request, 'news/index.html',
                  {
        'news': page_obj,
        'title': 'Список новостей',
        "all_category": all_category,
                  })


# Метод для получения айпи
def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR') # В REMOTE_ADDR значение айпи пользователя
    return ip


def detail(request ,pk):
    news = get_object_or_404(News, pk=pk)
    ip = get_client_ip(request)
    obj, created = Ip.objects.get_or_create(ip=ip)
    news.views.add(obj)
    template = 'news/detail.html'

    all_category = cache.get_or_set("all_category",Category.objects.all(),100)

    #if (News.objects.filter(id__gt=pk).first() and News.objects.filter(id__lt=pk).first()):
    #   earliest_news = News.objects.filter(id__lt=pk).first()
    #   latest_news = News.objects.filter(id__gt=pk).first()

    content = {
        "all_category": all_category,
        "five_latest_news": News.objects.order_by('-created_ad')[:5],
        "news":news,
                     }
    return render(request,template,content)


def category(request, category_id):
    all_category = cache.get_or_set("all_category", Category.objects.all(),100)
    category = get_object_or_404(Category, pk=category_id)
    news = category.news_set.select_related('autor').all()

    paginator = Paginator(news, 5)
    page_number = request.GET.get('page', 1)
    page_obj = paginator.get_page(page_number)
    return render(request, 'news/category.html',
                  {
    "news": page_obj,
    "category": category,
    "all_category": all_category
                  })



def add_like(request, news_id):
    """Лайкает `obj`.
    """
    if request.user.is_authenticated:
        news_object = get_object_or_404(News, pk=news_id)
        if Likes.objects.filter(news=news_object.id, user=request.user):
            Likes.objects.filter(
                news=news_object.id, user=request.user
            ).delete()
            return render(request, "news/detail.html",
                          {
                "category": Category.objects.all(),
                "five_latest_news": News.objects.order_by('-created_ad')[:5],
                "news": news_object,
                          })
        else:
            like = Likes.objects.get_or_create(news=news_object, user=request.user)
            return render(request,"news/detail.html",
                          {
                "like": like,
                "category": Category.objects.all(),
                "five_latest_news": News.objects.order_by('-created_ad')[:5],
                "news":news_object,
                          })
    else:
        return redirect('/login/')

mysite/news/templates/news/category.html
{% extends 'news/index.html'%}
{%block category%}
{%for item in all_category%}
    <div class="col">
        <a href="{%url 'news:category' item.id%}"><button class="btn btn-outline-dark px-5">{{item.title}}</button></a>
    </div>
{%endfor%}
{%endblock category%}
{%block content%}
<h2><div class="text-center" style="color: #000000;">{{category.title}}</div></h2>

<div class="container">
<div class="row">
  {%for item in news%}
    <div class="col-sm-4">
    <div class="card mt-3" style="background-color: #A9A9A9;">
      <div class="card-body">
          <div class="media">
              <div class="text-center"><h5 class="card-title text-dark">{{item.title}}</h5></div>
              {%if item.photo%}
              <img src="{{item.photo.url}}" alt='' width="320" height="300" class="mr-3">
              {% else %}
              <img src='https://picsum.photos/id/237/320/300' alt=''>
              {% endif %}
              <div class="media-body">
                  <p class="card-text text-dark">{{item.title_content}}</p>
                  <a href="{% url 'news:detail' item.id%}" class="btn btn-dark text-whit">read more..</a>
              </div>
          </div>
      </div>
    <div class="card-footer text-dark">{{item.created_ad|timesince}}-{{item.autor}}</div>
    </div>
    </div>
  {%endfor%}
</div>
</div>




<ul class="pagination pagination-lg justify-content-center">
    {% if news.has_previous %}
        <li class="page-item ">
            <a class="page-link text-secondary" href='/category/{{category.id}}?page={{news.previous_page_number}}'>Назад</a>
        </li>
    {% endif %}

    {%for item in news.paginator.page_range%}
        <li class="page-item">
            <a class="page-link text-secondary" href='/category/{{category.id}}?page={{item}}'>{{item}}
            </a>
        </li>
    {%endfor%}

    {% if news.has_next %}
        <li class="page-item ">
          <a class="page-link text-secondary" href='/category/{{category.id}}?page={{news.next_page_number}}'>Вперед</a>
        </li>
    {% endif %}

</ul>
{% endblock content %}

mysite/news/templates/news/create.html
{% extends 'news/index.html'%}
{% load static %}
{%block css%}

{%endblock css%}


{%block content%}



<div class="mx-3">
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}<br>
        {{form.title}}<br>
        {{form.category}}<br>
        {{form.title_content}}<br>
        {{form.content}}<br>
        {{form.created_ad}}<br>
        {{form.photo}}<br>

        <span>{{ eror }}</span>
        <button class="btn btn-success" type="submit">опубликовать</button>
    </form>
</div>
{% endblock content%}

mysite/news/templates/news/del.html
{% extends 'news/index.html'%}
{%block css%}
{% load static %}

{%endblock css%}




{%block content%}
<div class="features">
    <form method="post" enctype="multipart/form-data" >
        <h1>Удалить статью</h1>
        {% csrf_token %}<br>
        <span>{{ eror }}</span>
        <button class="btn btn-success" type="submit">удалить статью</button>
    </form>
</div>


{%endblock content%}

mysite/news/templates/news/detail.html
{% extends 'news/index.html'%}
{{block.super }}
{%block content%}

<div class="container-fluid">
  <div class="row">
    <div class="col">
      <div class="card text-dark w-85 mx-5 mb-5 px-5 mt-3 " style="background-color: #A9A9A9;" >
        <div class="card-body">
          <h5 class="card-title text-center">{{news.title}}</h5>
          <p class="card-text ">{{news.content|safe}}</p>
        </div>


        <div class="card-footer">
        {% if  request.user == news.autor %}
          <a href="{%url 'news:update' news.id%}" class="btn btn-dark text-whit">обновить</a>
          <a href="{%url 'news:delete' news.id%}" class="btn btn-dark text-whit">удалить</a>
        {%endif%}
          <a href="{%url 'news:add' news.id%}" class="btn btn-dark text-whit">
            лайкнуть <span class="badge bg-secondary">{{news.total_likes}}</span>
          </a>
          <a href="#" class="btn btn-dark text-whit">
            просмотрено <span class="badge bg-secondary">{{news.total_views}}</span>
          </a>
        </div>

   </div>
    </div>


    <div class="col-4">
    {%for item in five_latest_news%}
      <div class="card mt-3" style="background-color: #A9A9A9;">
      <div class="card-body">
        <div class="media">
        <div class="text-center"><h5 class="card-title text-dark">{{item.title}}</h5></div>
        {%if item.photo%}
        <img src="{{item.photo.url}}" alt='' width="390" height="300" class="mr-3">
        {% else %}
        <img src='https://picsum.photos/id/237/390/300' alt=''>
        {% endif %}
          <div class="media-body">
          <p class="card-text text-dark">{{item.title_content}}</p>
          <a href="{% url 'news:detail' item.id%}" class="btn btn-dark text-whit">read more..</a>
          </div>
        </div>
      </div>
      </div>
    {%endfor%}
    </div>

  </div>
</div>

{%endblock%}

mysite/news/templates/news/emailvalid.html
{% extends 'news/index.html'%}


{% load static %}
{%block css%}
 <link rel="stylesheet" href='{%static "news/main.css"%}'>
{%endblock css%}
{%block content%}

<div class="alert alert-success mb-0" role="alert">
    Пожалуйста подтвердите почту, чтобы добавлять новости на сайт
</div>

<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <p>{{form.email}}</p>
    <p>{{form.captcha}}</p>
    <button class="btn btn-success" type="submit">подтвердить</button>
</form>


{% endblock content%}

mysite/news/templates/news/forgot_password.html
{% extends 'news/index.html'%}


{% load static %}
{%block css%}
 <link rel="stylesheet" href='{%static "news/main.css"%}'>
{%endblock css%}

{%block content%}

<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <p>{{form.as_p}}</p>
    <button class="btn btn-success" type="submit">подтвердить</button>
</form>


{% endblock content%}

mysite/news/templates/news/index.html
<!doctype html>
{%block stati%} {%endblock stati%}
<html lang="en">
  <head>
    <meta charset="utf-8">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KyZXEAg3QhqLMpG8r+8fhAXLRk2vvoC2f3B09zVXn8CA5QIVfZOJ3BCsw2P0p/We" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/css/bootstrap-select.min.css">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap-select@1.13.14/dist/js/bootstrap-select.min.js"></script>
    {%block css%} {%endblock css%}
    <title> Новости</title>
<nav class="navbar navbar-expand-lg navbar-light " style="background-color: #A9A9A9;">
<div class="container-fluid">
    <a class="navbar-brand" href="{%url 'news:index'%}">Новости</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'news:index'%}">Главная</a></li>
          {%if request.user.is_staff %}
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'news:create'%}">Добавить новость</a></li>

          {%elif request.user.is_authenticated%}
            <li class="nav-item"><a class="nav-link active" aria-current="page" href="{%url 'news:emailvalid'%}">Подтвердите почту</a></li>
          {% endif %}
          {% if  request.user.is_authenticated %}
        <li class="nav-item"><a class="nav-link active" aria-current="page" href='{% url "news:account_logout" %}'>Выход ({{request.user}})</a></li>
          {%else%}
          <li class="nav-item"><a class="nav-link active" aria-current="page" href='{% url "news:account_signup" %}'>Регистрация</a></li>
          <li class="nav-item"><a class="nav-link active" aria-current="page" href='{% url "news:account_login" %}'>Вход</a></li>
          {%endif%}
      </ul>
    </div>
    <form class="d-flex" method="get" action="{% url 'news:search'%}" >
<input class="form-control me-2" type="text" name="q" aria-label="Search" value="" >
<button class="btn btn-outline-dark" type="submit">Search</button>
    </form>
  </div>
</nav>
</head>



<body class="bg-secondary text-white">

<div class="container-fluid">
  <div class="row">
     {%block category%}
      {%for item in all_category%}
    <div class="col">
        <a href="{%url 'news:category' item.id%}"><button class="btn btn-outline-dark px-5">{{item.title}}</button></a>
    </div>
      {%endfor%}
      {%endblock category%}
  </div>
</div>

{% if messages %}
    {% for massage in messages %}
        {% if massage.tags == "error" %}
            <div class="alert alert-danger mb-0" role="alert">
                {{massage}}
            </div>
        {% else %}
            <div class="alert alert-{{massage.tags}} mb-0" role="alert">
                {{massage}}
            </div>
        {% endif %}
    {% endfor %}
{% endif %}

{% block head_title %}{% endblock %}


{%block content%}




<div class="container mb-5">
<div class="row">
  {%for item in news%}
    <div class="col-sm-4">
    <div class="card mt-3" style="background-color: #A9A9A9; max-height:600px">
      <div class="card-body">
          <div class="media">
              <div class="text-center"><h5 class="card-title text-dark">{{item.title}}</h5></div>
              {%if item.photo%}
              <img src="{{item.photo.url}}" alt='' max-width="330" width="90%" height="90%" max-height="320px" class="mr-3">
              {% else %}
              <img src='https://nos.twnsnd.co/image/697559999966314497' alt=''>
              {% endif %}
              <div class="media-body">
                  <p class="card-text text-dark">{{item.title_content}}</p>
                  <a href="{% url 'news:detail' item.id%}" class="btn btn-dark text-whit">read more..</a>
              </div>
          </div>
      </div>
    <div class="card-footer text-dark">{{item.created_ad}}-{{item.autor}} </div>
    </div>
    </div>
  {%endfor%}
</div>
</div>




<ul class="pagination pagination-lg justify-content-center">
    {% if news.has_previous %}
        <li class="page-item ">
            <a class="page-link text-secondary" href='?page={{news.previous_page_number}}'>Назад</a>
        </li>
    {% endif %}

    {%for item in news.paginator.page_range%}
        <li class="page-item">
            <a class="page-link text-secondary" href='?page={{item}}'>{{item}}
            </a>
        </li>
    {%endfor%}

    {% if news.has_next %}
        <li class="page-item ">
          <a class="page-link text-secondary" href='?page={{news.next_page_number}}'>Вперед</a>
        </li>
    {% endif %}

</ul>
{% endblock content %}


    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.bundle.min.js" integrity="sha384-U1DAWAznBHeqEIlVSCgzq+c9gqGAJn5c/t99JyeKa9xxaYpSvHU5awsuZVVFIhvj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-eMNCOe7tC1doHpGoWe/6oMVemdAVTMs2xqW4mwXrXsW0L84Iytr2wi5v2QjrP/xp" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.0/dist/js/bootstrap.min.js"   integrity="sha384-cn7l7gDp0eyniUwwAZgrzD06kc/tftFf19TOAs2zVinnD/C7E91j9yyk5//jjpt/" crossorigin="anonymous"></script>
</body>
</html>

mysite/news/templates/news/login.html
{% extends 'news/index.html'%}

{% load static %}
{%block css%}
 <link rel="stylesheet" href='{%static "news/main.css"%}'>
{%endblock css%}
{%block content%}


<p>
<div class="features">
    <form method="post" enctype="multipart/form-data" >
        {% csrf_token %}
        <p>{{form.username}}</p>
        <p>{{form.password}}</p>
        <p>{{form.captcha}}</p>
        <button class="btn btn-success" type="submit">Войти</button>
        <a href="{%url 'news:forgot_password'%}" class="btn btn-dark ">Забыли пароль</a>
    </form>
</div>

{% endblock content%}}

mysite/news/templates/news/password_valid.html
{% extends 'news/index.html'%}


{% load static %}
{%block css%}
 <link rel="stylesheet" href='{%static "news/main.css"%}'>
{%endblock css%}
{%block content%}
<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <p>{{form.as_p}}</p>
    <button class="btn btn-success" type="submit">подтвердить</button>
</form>
<br>
{% endblock content%}

mysite/news/templates/news/registr.html
{% extends 'news/index.html'%}

{% load static %}
{%block css%}
 <link rel="stylesheet" href='{%static "news/main.css"%}'>
{%endblock css%}

{%block content%}

<!--
{% if email %}
<h2>Мы отправили на вашу почту {{email}} сообщение с кодом для подтверждения</h2>
<h3> Введите пожалуйтса код </h3>

<form method="post" action="{%url 'news:account_validate' user.id%}" enctype="multipart/form-data" >
    {% csrf_token %}
    <p>{{form.code}}</p>
    <button class="btn btn-success" type="submit">подтвердить</button>
</form>

{%endif%}
{{else}}{{endelse}}
-->
<form method="post" enctype="multipart/form-data" >
    <p>{% csrf_token %}</p>
    <p>{{form.username}}</p>
    <p>{{form.email}}</p>
    <p>{{form.password1}}</p>
    <p>{{form.password2}}</p>
    <p>{{form.captcha}}</p>
    <button class="btn btn-success" type="submit">Зарегистрироваться</button>
</form>
<br>




{% endblock content%}

mysite/news/templates/news/search.html
{% extends 'news/index.html'%}
{{block.super }}
{%block content%}


<div class="container mb-5">
<div class="row">
  {%if not news%}
    <h1>{{looos}}{{q}}</h1>
  {%endif%}
  {%for item in news%}
    <div class="col-sm-4">
    <div class="card mt-3" style="background-color: #A9A9A9;">
      <div class="card-body">
          <div class="media">
              <div class="text-center"><h5 class="card-title text-dark">{{item.title}}</h5></div>
              {%if item.photo%}
              <img src="{{item.photo.url}}" alt='' width="320" height="400" class="mr-3">
              {% else %}
              <img src='https://picsum.photos/id/237/320/400' alt=''>
              {% endif %}
              <div class="media-body">
                  <p class="card-text text-dark">{{item.title_content}}</p>
                  <a href="{% url 'news:detail' item.id%}" class="btn btn-dark text-whit">read more..</a>
              </div>
          </div>
      </div>
    <div class="card-footer text-dark">{{item.created_ad}}-{{item.autor}} </div>
    </div>
    </div>
  {%endfor%}
</div>
</div>
{%endblock content%}

mysite/news/templates/news/users.html
{% extends 'news/index.html'%}
{{block.super }}
{%block content%}

{% for item in User%}
    {{item.username}}==={{item.id}}</p>
{%endfor%}
{%endblock%}

mysite/news/templates/news/vaild.html
{% extends 'news/index.html'%}


{% load static %}
{%block css%}
 <link rel="stylesheet" href='{%static "news/main.css"%}'>
{%endblock css%}
{%block content%}



<form method="post" enctype="multipart/form-data" >
    {% csrf_token %}
    <p>{{form.as_p}}</p>
    <button class="btn btn-success" type="submit">подтвердить</button>
<a href="/" class="btn btn-dark text-whit">Подтвертить почту позже</a>
</form>

{% endblock content%}